# Generated by Django 4.1.5 on 2023-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contents', models.TextField()),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content Block',
                'verbose_name_plural': 'Page Content Blocks',
                'abstract': False,
            },
        ),
    ]
